cmake_minimum_required(VERSION 4.1)
project(mProg1)

set(CMAKE_CXX_STANDARD 14)

add_executable(mProg1
        szorgalmik/bouncing_ball.cpp
        szorgalmik/gyak8.cpp
        gyak2.cpp
        gyak7_1.cpp
        gyak8.cpp
        prog1.cpp
        ai-feladatok.cpp
        "ai-feladatok_2.cpp"
        ai-feladatok_3.cpp
        ai-feladatok_4.cpp
        ai-feladatok-05.cpp)
